# Generated by Django 4.0.5 on 2022-07-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(default='billing', unique=True),
            preserve_default=False,
        ),
    ]
