# Generated by Django 4.0.5 on 2022-07-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicecategory_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='category',
            new_name='name',
        ),
    ]
