# Generated by Django 4.0.5 on 2022-07-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_servicecategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='categories',
            new_name='category',
        ),
    ]
